sonar.organization=zafnok
sonar.projectKey=Zafnok_tactical-rpg
sonar.sources=crates
sonar.tests=crates
sonar.test.inclusions=**/tests/**,**/*_test.rs
sonar.exclusions=target/**,crates/app/**
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippy.reportPaths=clippy.json
