//! The font atlas (`assets/fonts/atlas.ron` + `atlas.png`, ADR-0012): a grid
//! of fixed-size glyph cells and the map from `char` to cell index.
//!
//! Both files are generated by `cargo xtask font-atlas` from the bitmap font
//! described in `assets/fonts/README.md`, and committed.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::bundle;
use crate::error::ContentError;
use crate::ron_loader::parse_ron;

/// Path of the glyph map inside the asset bundle.
pub const ATLAS_PATH: &str = "fonts/atlas.ron";
/// Path of the atlas image (white glyphs on transparent) inside the bundle.
pub const ATLAS_PNG_PATH: &str = "fonts/atlas.png";

/// Glyphs the game draws and the atlas must therefore contain: printable
/// ASCII, Latin-1, box drawing, blocks and the CP437-style symbols used by
/// maps and UI (ADR-0012).
pub const REQUIRED_GLYPHS: &str = concat!(
    // Printable ASCII.
    " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`",
    "abcdefghijklmnopqrstuvwxyz{|}~",
    // Latin-1 supplement (the U+00AD soft hyphen is invisible, so escaped).
    "¡¢£¤¥¦§¨©ª«¬\u{ad}®¯°±²³´µ¶·¸¹º»¼½¾¿",
    "ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß",
    "àáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ",
    // Box drawing.
    "─│┌┐└┘├┤┬┴┼═║╔╗╚╝╠╣╦╩╬",
    // Blocks and bars.
    "░▒▓█▀▄▌▐■",
    // Symbols (the ticket also lists · and ¤, which are Latin-1 above).
    "♣♠♥♦≈•ˇ▲▼◄►←↑→↓☺☻♪†",
);

/// The glyph used when a cell's glyph is not in the atlas.
pub const FALLBACK_GLYPH: char = '?';

/// The validated font atlas layout.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct FontAtlasDef {
    /// Cell width in pixels.
    pub cell_w: u32,
    /// Cell height in pixels.
    pub cell_h: u32,
    /// Cells per atlas row.
    pub columns: u32,
    /// Every glyph in the atlas → its cell index (row-major).
    pub glyphs: BTreeMap<char, u32>,
}

/// A pixel rectangle inside the atlas image.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AtlasRect {
    /// Left edge in pixels.
    pub x: u32,
    /// Top edge in pixels.
    pub y: u32,
    /// Width in pixels.
    pub w: u32,
    /// Height in pixels.
    pub h: u32,
}

impl FontAtlasDef {
    /// The pixel rectangle of cell `index`. `columns` must be non-zero (a
    /// validated atlas guarantees it).
    pub fn cell_rect(&self, index: u32) -> AtlasRect {
        AtlasRect {
            x: index % self.columns * self.cell_w,
            y: index / self.columns * self.cell_h,
            w: self.cell_w,
            h: self.cell_h,
        }
    }

    /// The pixel rectangle of glyph `c`, or `None` if the atlas lacks it.
    pub fn glyph_rect(&self, c: char) -> Option<AtlasRect> {
        self.glyphs.get(&c).map(|&i| self.cell_rect(i))
    }

    /// Loads and validates the embedded glyph map against the embedded image.
    pub fn load() -> Result<Self, Vec<ContentError>> {
        let display = bundle::display_path(ATLAS_PATH);
        let source = bundle::file(ATLAS_PATH).ok_or_else(|| {
            vec![ContentError::new(
                &display,
                "file not found in asset bundle",
            )]
        })?;
        Self::from_source(&display, source, bundle::bytes(ATLAS_PNG_PATH))
    }

    /// Parses glyph map `source` (errors attributed to `file`) and validates
    /// it, including against the atlas image `png` (`None` if missing).
    pub fn from_source(
        file: &str,
        source: &str,
        png: Option<&[u8]>,
    ) -> Result<Self, Vec<ContentError>> {
        let def: Self = parse_ron(file, source).map_err(|e| vec![e])?;
        let mut errors: Vec<ContentError> = def
            .problems()
            .into_iter()
            .map(|m| ContentError::new(file, m))
            .collect();
        let png_file = bundle::display_path(ATLAS_PNG_PATH);
        match png.map(png_size) {
            None => errors.push(ContentError::new(
                &png_file,
                "file not found in asset bundle",
            )),
            Some(None) => errors.push(ContentError::new(&png_file, "not a valid PNG file")),
            Some(Some((w, h))) => errors.extend(
                def.image_problems(w, h)
                    .into_iter()
                    .map(|m| ContentError::new(&png_file, m)),
            ),
        }
        if errors.is_empty() {
            Ok(def)
        } else {
            Err(errors)
        }
    }

    /// Problems with the glyph map on its own, in plain words.
    pub fn problems(&self) -> Vec<String> {
        let mut out = Vec::new();
        for (name, v) in [
            ("cell_w", self.cell_w),
            ("cell_h", self.cell_h),
            ("columns", self.columns),
        ] {
            if v == 0 {
                out.push(format!("{name} must be greater than 0"));
            }
        }
        let missing: Vec<String> = REQUIRED_GLYPHS
            .chars()
            .filter(|c| !self.glyphs.contains_key(c))
            .map(describe)
            .collect();
        if !missing.is_empty() {
            out.push(format!("missing required glyphs: {}", missing.join(", ")));
        }
        let mut owner: BTreeMap<u32, char> = BTreeMap::new();
        for (&c, &i) in &self.glyphs {
            if let Some(&first) = owner.get(&i) {
                out.push(format!(
                    "{} and {} share cell index {i}",
                    describe(first),
                    describe(c)
                ));
            } else {
                owner.insert(i, c);
            }
        }
        out
    }

    /// Problems fitting the glyph map onto a `width × height` pixel image.
    pub fn image_problems(&self, width: u32, height: u32) -> Vec<String> {
        if self.cell_w == 0 || self.cell_h == 0 || self.columns == 0 {
            return Vec::new(); // Already reported by `problems`.
        }
        let mut out = Vec::new();
        let expected_w = u64::from(self.columns) * u64::from(self.cell_w);
        if u64::from(width) != expected_w {
            out.push(format!(
                "image is {width} px wide, expected {expected_w} (columns × cell_w)"
            ));
        }
        if !height.is_multiple_of(self.cell_h) {
            out.push(format!(
                "image height {height} px is not a multiple of cell_h {}",
                self.cell_h
            ));
        }
        let cells = u64::from(self.columns) * u64::from(height / self.cell_h);
        if let Some((&c, &i)) = self.glyphs.iter().find(|&(_, &i)| u64::from(i) >= cells) {
            out.push(format!(
                "{} has cell index {i}, but the image only holds {cells} cells",
                describe(c)
            ));
        }
        out
    }
}

/// `'x' (U+0078)`, readable even for invisible or confusable glyphs.
fn describe(c: char) -> String {
    format!("'{}' (U+{:04X})", c.escape_debug(), u32::from(c))
}

/// Width and height from a PNG's header, or `None` if `bytes` isn't a PNG.
pub fn png_size(bytes: &[u8]) -> Option<(u32, u32)> {
    const SIGNATURE: &[u8] = b"\x89PNG\r\n\x1a\n";
    // Signature, then the IHDR chunk: length (4), type (4), width (4), height (4).
    let header = bytes.get(..24)?;
    if &header[..8] != SIGNATURE || &header[12..16] != b"IHDR" {
        return None;
    }
    let be = |at: usize| {
        u32::from_be_bytes([header[at], header[at + 1], header[at + 2], header[at + 3]])
    };
    Some((be(16), be(20)))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A valid atlas holding exactly the required glyphs, 16 per row.
    fn required_only() -> FontAtlasDef {
        FontAtlasDef {
            cell_w: 8,
            cell_h: 16,
            columns: 16,
            glyphs: REQUIRED_GLYPHS.chars().zip(0..).collect(),
        }
    }

    fn png_header(w: u32, h: u32) -> Vec<u8> {
        let mut v = b"\x89PNG\r\n\x1a\n\0\0\0\x0dIHDR".to_vec();
        v.extend(w.to_be_bytes());
        v.extend(h.to_be_bytes());
        v.extend([8, 6, 0, 0, 0]);
        v
    }

    fn rows_for(def: &FontAtlasDef) -> u32 {
        let n = u32::try_from(def.glyphs.len()).unwrap_or(u32::MAX);
        n.div_ceil(def.columns)
    }

    #[test]
    fn required_glyphs_cover_ascii_and_latin1() {
        let set: Vec<char> = REQUIRED_GLYPHS.chars().collect();
        for c in (' '..='~').chain('\u{a1}'..='\u{ff}') {
            assert!(set.contains(&c), "missing {}", describe(c));
        }
        let mut unique = set.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(unique.len(), set.len(), "duplicates in REQUIRED_GLYPHS");
        assert!(set.contains(&FALLBACK_GLYPH));
    }

    #[test]
    fn cell_and_glyph_rects() {
        let def = FontAtlasDef {
            cell_w: 8,
            cell_h: 16,
            columns: 32,
            glyphs: [('a', 0), ('b', 31), ('c', 32), ('d', 70)].into(),
        };
        let r = |x, y| Some(AtlasRect { x, y, w: 8, h: 16 });
        assert_eq!(def.glyph_rect('a'), r(0, 0));
        assert_eq!(def.glyph_rect('b'), r(248, 0));
        assert_eq!(def.glyph_rect('c'), r(0, 16));
        assert_eq!(def.glyph_rect('d'), r(48, 32));
        assert_eq!(def.glyph_rect('z'), None);
    }

    #[test]
    fn valid_atlas_has_no_problems() {
        let def = required_only();
        assert_eq!(def.problems(), Vec::<String>::new());
        let rows = rows_for(&def);
        assert_eq!(def.image_problems(128, rows * 16), Vec::<String>::new());
    }

    #[test]
    fn zero_sizes_are_problems() {
        let mut def = required_only();
        def.cell_w = 0;
        def.columns = 0;
        assert_eq!(
            def.problems(),
            [
                "cell_w must be greater than 0",
                "columns must be greater than 0"
            ]
        );
        assert!(def.image_problems(0, 0).is_empty());
        let mut def = required_only();
        def.cell_h = 0;
        assert_eq!(def.problems(), ["cell_h must be greater than 0"]);
        assert!(def.image_problems(0, 0).is_empty());
    }

    #[test]
    fn missing_required_glyphs_listed_together() {
        let mut def = required_only();
        def.glyphs.remove(&'♣');
        def.glyphs.remove(&'\'');
        assert_eq!(
            def.problems(),
            ["missing required glyphs: '\\'' (U+0027), '♣' (U+2663)"]
        );
    }

    #[test]
    fn shared_index_is_problem() {
        let mut def = required_only();
        def.glyphs.insert('\u{2603}', 0);
        assert_eq!(
            def.problems(),
            ["' ' (U+0020) and '☃' (U+2603) share cell index 0"]
        );
    }

    #[test]
    fn image_size_problems() {
        let def = required_only();
        let rows = rows_for(&def);
        assert_eq!(
            def.image_problems(120, rows * 16),
            ["image is 120 px wide, expected 128 (columns × cell_w)"]
        );
        assert_eq!(
            def.image_problems(128, rows * 16 + 3),
            [format!(
                "image height {} px is not a multiple of cell_h 16",
                rows * 16 + 3
            )]
        );
        let cells = (rows - 1) * 16;
        // One row short: (rows - 1) rows of 16 px hold (rows - 1) × 16 cells.
        let problems = def.image_problems(128, (rows - 1) * 16);
        assert_eq!(problems.len(), 1, "{problems:?}");
        assert!(
            problems[0].ends_with(&format!("but the image only holds {cells} cells")),
            "{problems:?}"
        );
    }

    #[test]
    fn png_size_reads_header() {
        assert_eq!(png_size(&png_header(256, 288)), Some((256, 288)));
        assert_eq!(png_size(&png_header(256, 288)[..23]), None);
        let mut bad = png_header(1, 1);
        bad[0] = 0;
        assert_eq!(png_size(&bad), None);
        let mut bad = png_header(1, 1);
        bad[12] = b'X';
        assert_eq!(png_size(&bad), None);
    }

    #[test]
    fn from_source_reports_file_and_image_errors() {
        let src = "(cell_w: 8, cell_h: 16, columns: 0, glyphs: {'a': 0})";
        let errs = FontAtlasDef::from_source("a.ron", src, None)
            .err()
            .unwrap_or_default();
        let text: Vec<String> = errs.iter().map(ToString::to_string).collect();
        assert_eq!(text.len(), 3, "{text:?}");
        assert_eq!(text[0], "a.ron: columns must be greater than 0");
        assert!(text[1].starts_with("a.ron: missing required glyphs: ' ' (U+0020)"));
        assert_eq!(
            text[2],
            "assets/fonts/atlas.png: file not found in asset bundle"
        );
        let errs = FontAtlasDef::from_source("a.ron", src, Some(b"nope"))
            .err()
            .unwrap_or_default();
        assert_eq!(
            errs.last().map(ToString::to_string).as_deref(),
            Some("assets/fonts/atlas.png: not a valid PNG file")
        );
    }

    #[test]
    fn from_source_ok_and_syntax_error() {
        let def = required_only();
        let src = ron::to_string(&def).unwrap_or_default();
        let png = png_header(128, rows_for(&def) * 16);
        assert_eq!(
            FontAtlasDef::from_source("a.ron", &src, Some(&png)),
            Ok(def)
        );
        let png = png_header(64, rows_for(&required_only()) * 16);
        let errs = FontAtlasDef::from_source("a.ron", &src, Some(&png))
            .err()
            .unwrap_or_default();
        assert_eq!(errs.len(), 1);
        assert_eq!(errs[0].file, "assets/fonts/atlas.png");
        let errs = FontAtlasDef::from_source("a.ron", "(cell_w: ", None)
            .err()
            .unwrap_or_default();
        assert_eq!(errs.len(), 1);
        assert!(errs[0].line.is_some());
    }

    #[test]
    fn embedded_atlas_loads_with_every_required_glyph() {
        let def = FontAtlasDef::load();
        assert!(def.is_ok(), "{def:?}");
        let def = def.unwrap_or_default();
        assert_eq!((def.cell_w, def.cell_h), (8, 16));
        for c in REQUIRED_GLYPHS.chars() {
            assert!(def.glyph_rect(c).is_some(), "missing {}", describe(c));
        }
    }
}
