[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license-file.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
trpg-content = { path = "../content" }
mutants = "0.0.4"
png = "0.17"
ron.workspace = true
serde_norway = "0.9.42"
